### ISSUE TITLE
FVCOM implementation and FVCOM+WW3 coupling issues

### ISSUE THREAD

**Issue by pvelissariou1** [noaa-ocs-modeling/CoastalApp#110]
@FVCOM-GitHub @awest-noaa @pvelissariou1 @saeed-moghimi-noaa @aliabdolali 

Item 1: Coupling FVCOM+WW3 configuration within CoastalApp 
            
- [ ] Fork from CoastalApp develop (https://github.com/noaa-ocs-modeling/CoastalApp/tree/develop)
- [ ] Add FVCOM submodule 
- [ ] Compile and test WW3 stand alone with ATM and with NUOPC cap with ATMESH  

### Information from Chat:
Andre Van der Westhuysen - NOAA Affiliate
11:13 AM
Do you model the jetties with subgrid structures?
Ali Abdolali - NOAA Affiliate
11:34 AM
you can export (water level) WLV and (depth) DPT in WW3 and check them for Coastal App vs WW3 stand alone
also, please use "git log" and check you are using the same versions. 
Ali Abdolali - NOAA Affiliate
11:37 AM
ww3_grid
Ali Abdolali - NOAA Affiliate
11:42 AM
vi .gitmodules
You
11:45 AM
https://github.com/noaa-ocs-modeling/CoastalApp
https://github.com/FVCOM-GitHub/CoastalApp
Ali Abdolali - NOAA Affiliate
11:54 AM
does atmmesh need more than 1 core?
Andre Van der Westhuysen - NOAA Affiliate
11:54 AM
No
You
11:54 AM
I think the new code need to be chcked for this as well.
Ali Abdolali - NOAA Affiliate
11:54 AM
awesome
Ali Abdolali - NOAA Affiliate
11:57 AM
DIST MPI
You
12:02 PM
Ali and andre please copy your github user here
Prof. chen
Pleas copy your github userid here
Andre Van der Westhuysen - NOAA Affiliate
12:02 PM
awest-noaa
Ali Abdolali - NOAA Affiliate
12:03 PM
aliabdolali
You
12:05 PM
Prof. chen, Pleas copy your github userid here
Ali Abdolali - NOAA Affiliate
12:05 PM
I need to run
have a great day
You
12:05 PM
Ok Ali
Thanks
Changsheng Chen
12:05 PM
Ali: Thanks.

**Comment by saeed-moghimi-noaa** [comment]
@FVCOM-GitHub @SorooshMani-NOAA @pvelissariou1 

Github commands from meeting chat and Dr. Qi history:

git clone -b mybranch --single-branch git://sub.domain.com/repo.git
Soroosh Mani - NOAA Affiliate
3:03 PM
git clone https://github.com/FVCOM-GitHub/CoastalApp
Soroosh Mani - NOAA Affiliate
3:04 PM
git clone -b feature/FVCOM --single-branch https://github.com/FVCOM-GitHub/CoastalApp
Soroosh Mani - NOAA Affiliate
3:25 PM
git submodule init
git submodule update --init --recursive


JIANHUA QI
3:32 PM
101  14:58   cd /data4/jqi
   103  14:58   cd CoastalApp_git20220531
   105  14:59   mkdir CoastalApp_backup
   107  15:00   cd CoastalApp_backup
   109  15:05   git clone https://github.com/FVCOM-GitHub/CoastalApp.git
   113  15:22   ll ../
   114  15:22   cd ../
   115  15:22   cd ..
   117  15:23   mv CoastalApp CoastalApp_main
   119  15:24   git clone -b feature/FVCOM --single-branch https://github.com/FVCOM-GitHub/CoastalApp
   121  15:25   cd CoastalApp

**Comment by saeed-moghimi-noaa** [comment]
@FVCOM-GitHub @pvelissariou1 @SorooshMani-NOAA @yangz888 

Dr. Qi, Please continue the coupling / CoastalApp conversation here.

Thanks,
-Saeed

![image](https://user-images.githubusercontent.com/66274703/181631433-9f7e37d8-3b58-4143-827f-083762571b48.png)

**Comment by saeed-moghimi-noaa** [comment]
PLEASE follow up here and do not communicate via emails

https://github.com/noaa-ocs-modeling/CoastalApp/discussions/150
