### ISSUE TITLE
Run PAHM + ADCIRC + WW3 + BARDATA

### ISSUE THREAD

**Issue by saeed-moghimi-noaa** [noaa-ocs-modeling/CoastalApp#111]

**Comment by saeed-moghimi-noaa** [comment]
@pvelissariou1 

Hi Takis,

Here are the current action items on the HS project:
- [ ] Run Florence for WW3+PAHM+ADCIRC  (work with @awest-noaa @aliabdolali) 
- [ ] Run BARATA+ ADCIRC for Florence  (work with @cblakely97)
- [ ]  Run BARATA+ ADCIRC + PAHM + WW3 for Florence
- [ ] Wrap up the report

Please update the team here on your progress / Status. 

Thanks,
@saeed-moghimi-noaa

**Comment by pvelissariou1** [comment]
Action items:
1) Generate the HYCOM/Baroclinic data file to be digested by ADCIRC/NUOPC Cap
2) Restructure the simulation configuration files to adjust the simulation start period
    a) to help WW3 simulation by removing a couple of days that have zero winds in the mesh
3) Get/Update the BARDATA and ADCIRC codes in CoastalApp
4) Share the generated data and the restructured simulation files with Andre so he can start the WW3 simulations early next week (WW3+PAHM+ADCIRC).
5) Run the BARATA+ ADCIRC [ + PAHM] simulations
6) Run BARATA+ ADCIRC + PAHM + WW3 (Andre will help on setting WW3 configs and BCs)

**Comment by pvelissariou1** [comment]
CoastalApp build system was enhanced to allow the compilation of thirdparty libraries like, datetime, metis, ...
1. ADCIRC with baroclinicity enabled can be built successfully
    a) ADCIRC was modified to fix issues with baroclinic builds; changes were pushed to adcirc-cg/cmmb and are waiting
        approval before merging with development
    b) ADCIRC+baroclinicity can be build in stand-alone and within NEMS/NUOPC configurations.
2. The HYCOM baroclinic input files have been generated for 3hr, 6hr, 12hr and 24hr (4 files) temporal intervals.
3. The simulation configuration files (fort.15, model*conf*, nems*conf*, ..) have been adjusted by extending the spinup period
     by two days (reducing the run period by 2 days; those days without winds in the domain)
4. CoastalApp is up to date (ADCIRC, BARDATA, build)
5. Data are shared on hera.
NOTE: MY ADCIRC changes are not yet merged with adcirc-cg/development (waiting for approval by Zach). I'll share my local copy with Andre on hera.
6. Simulations ADCIRC+PAHM, ADCIRC+PAHM+BARDATA are to be submitted tomorrow.

**Comment by pvelissariou1** [comment]
1. Simulations PAHM+ADCIRC, PAHM+ADCIRC+BARDATA are completed
2. Zach will incorporate my changes into adcirc-cg/development after the regression tests are complete (the tests are running at this time)
3. All required data for Andre (including configs with/without baroclinicity are on hera)
4. I will talk with him tomorrow to see how we can proceed with WW3

**Comment by pvelissariou1** [comment]
Updates on ADCIRC+PAHM and ADCIRC+BARDATA+PAHM
1) ADCIRC+PAHM
Produces warnings that the water level exceeds the Warn Elevation Level, example:
```
 TIME STEP =  402609     ITERATIONS =   15     TIME =  0.80521800E+06
  ELMAX = -3.7782E+001 AT NODE  3640963  SPEEDMAX =  7.4168E+000 AT NODE  3594879  ON MYPROC =  150   ** WARNING: Elevation.gt.WarnElev **
 TIME STEP =  402609     ITERATIONS =   15     TIME =  0.80521800E+06
  ELMAX = -3.6153E+001 AT NODE  3735005  SPEEDMAX =  7.8532E+000 AT NODE  3997253  ON MYPROC =  149   ** WARNING: Elevation.gt.WarnElev **
 TIME STEP =  402610     ITERATIONS =   15     TIME =  0.80522000E+06
  ELMAX = -3.7808E+001 AT NODE  3640963  SPEEDMAX =  7.4257E+000 AT NODE  3594879  ON MYPROC =  150   ** WARNING: Elevation.gt.WarnElev **
```

```
 TIME STEP =  820800 100.00% COMPLETE     ITERATIONS =   17     TIME =  0.16416000E+07
  ELMAX =  5.0922E+000 AT NODE     5567  SPEEDMAX =  1.7314E+000 AT NODE     5577  ON MYPROC =    0
_______________________________________________________________
Start Epilog v20.08.28 on node h14c10 for job 32780997 :: Tue Jun 14 11:22:31 UTC 2022
Job 32780997 (not serial) finished for user Panagiotis.Velissariou in partition hera with exit code 0:0
_______________________________________________________________
End Epilogue v20.08.28 Tue Jun 14 11:22:31 UTC 2022
```

2) ADCIRC+BARDATA+PAHM
Produces warnings that the water level exceeds the Warn Elevation Level, example:
```
TIME STEP =  768284     ITERATIONS =   12     TIME =  0.15365680E+07
  ELMAX =  1.3743E+002 AT NODE  2508774  SPEEDMAX =  1.4238E+002 AT NODE  2482398  ON MYPROC =   16   ** WARNING: Elevation.gt.WarnElev **
```
and finally the simulation crashes toward the end of the simulation:
```
 TIME STEP =  769306     ITERATIONS =   12     TIME =  0.15386120E+07
  ELMAX =  1.0043E+003 AT NODE  2482395  SPEEDMAX =  3.5058E+002 AT NODE  2482398  ON MYPROC =   16
  ** ERROR: Elevation.gt.ErrorElev, ADCIRC stopping. **
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 32781007.0 ON h1c08 CANCELLED AT 2022-06-14T16:10:43 DUE TO TIME LIMIT ***
slurmstepd: error: *** JOB 32781007 ON h1c08 CANCELLED AT 2022-06-14T16:10:43 DUE TO TIME LIMIT ***
```

```
 TIME STEP =  769100  88.03% COMPLETE     ITERATIONS =   12     TIME =  0.15382000E+07
  ELMAX =  5.0405E+000 AT NODE     5567  SPEEDMAX =  1.3994E+000 AT NODE     5577  ON MYPROC =    0
 TIME STEP =  769200  88.06% COMPLETE     ITERATIONS =   12     TIME =  0.15384000E+07
  ELMAX =  5.0574E+000 AT NODE     5567  SPEEDMAX =  1.3625E+000 AT NODE     5577  ON MYPROC =    0
 TIME STEP =  769300  88.08% COMPLETE     ITERATIONS =   12     TIME =  0.15386000E+07
  ELMAX =  5.0701E+000 AT NODE     5567  SPEEDMAX =  1.3308E+000 AT NODE     5577  ON MYPROC =    0
_______________________________________________________________
Start Epilog v20.08.28 on node h1c08 for job 32781007 :: Tue Jun 14 16:10:49 UTC 2022
Job 32781007 (not serial) finished for user Panagiotis.Velissariou in partition hera with exit code 0:15
_______________________________________________________________
End Epilogue v20.08.28 Tue Jun 14 16:10:49 UTC 2022
```

**Comment by saeed-moghimi-noaa** [comment]
Hi @cblakely97 @GM-Ling @pvelissariou1 

Would you please take look at this issue? 

Thanks,
@saeed-moghimi-noaa

**Comment by cblakely97** [comment]
@pvelissariou1 Have you run just ADCIRC+BARDATA? What time step does the ADCIRC+BARDATA+PAHM go unstable? Is it earlier or later than ADCIRC+PAHM? What time step are you using? What other input parameters do you use? Is this different than the simulation you said was done on the 9th?

**Comment by saeed-moghimi-noaa** [comment]
@cblakely97 @pvelissariou1  @jwesterink @GM-Ling

Please continue the discussion here ----   Copied from Email:

Hello Coleman, Joannes

This is my first update

With the updated fort.13/fort.14 files I get the elevation warning messages:
** WARNING: Elevation.gt.WarnElev **
even with the spinup (no baroclinic effects) now.
I started receiving these messages about 1.25% into the spinup simulation.
I switched NRAMP from 1 to 8 and the warning messages appear ~4.5%
into the simulation.

Any ideas/suggestions?

In the original fort.15 file I had:
-------------------- previous fort.15 --------------------
3                                               ! NWP     - VARIABLE BOTTOM FRICTION AND LATERAL VISCOSITY OPTION PARAMETER; default 0
internal_tide_friction
quadratic_friction_coefficient_at_sea_floor
primitive_weighting_in_continuity_equation
1                                               ! NCOR    - VARIABLE CORIOLIS IN SPACE OPTION PARAMETER
1                                               ! NTIP    - TIDAL POTENTIAL OPTION PARAMETER
0                                               ! NWS     - WIND STRESS AND BAROMETRIC PRESSURE OPTION PARAMETER
1                                               ! NRAMP   - RAMP FUNCTION OPTION
------------------------------------------------------------

In the current fort.15 file I have:
-------------------- current fort.15 --------------------
8                                               ! NWP     - VARIABLE BOTTOM FRICTION AND LATERAL VISCOSITY OPTION PARAMETER; default 0
primitive_weighting_in_continuity_equation
mannings_n_at_sea_floor
internal_tide_friction
subgrid_barrier
surface_submergence_state
surface_canopy_coefficient
advection_state
surface_directional_effective_roughness_length
1                                               ! NCOR    - VARIABLE CORIOLIS IN SPACE OPTION PARAMETER
1                                               ! NTIP    - TIDAL POTENTIAL OPTION PARAMETER
0                                               ! NWS     - WIND STRESS AND BAROMETRIC PRESSURE OPTION PARAMETER
8                                               ! NRAMP   - RAMP FUNCTION OPTION
------------------------------------------------------------

Thank you
Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Project Lead - Coastal Coupling
cell: (205) 227-9141
email: [panagiotis.velissariou@noaa.gov](mailto:panagiotis.velissariou@noaa.gov)


On Wed, Jun 22, 2022 at 8:34 AM Coleman Blakely <[Coleman.P.Blakely.5@nd.edu](mailto:Coleman.P.Blakely.5@nd.edu)> wrote:



    On Wed, Jun 22, 2022 at 9:18 AM Panagiotis Velissariou - NOAA Affiliate <[panagiotis.velissariou@noaa.gov](mailto:panagiotis.velissariou@noaa.gov)> wrote:

        Thank you Coleman.
        Could you please share the corresponding fort.15 as well?

        Takis

        Panagiotis Velissariou, Ph.D., P.E.
        UCAR Scientist
        National Ocean and Atmospheric Administration
        National Ocean Service
        Office of Coast Survey CSDL/CMMB
        Project Lead - Coastal Coupling
        cell: (205) 227-9141
        email: [panagiotis.velissariou@noaa.gov](mailto:panagiotis.velissariou@noaa.gov)


        On Tue, Jun 21, 2022 at 2:26 PM Coleman Blakely <[Coleman.P.Blakely.5@nd.edu](mailto:Coleman.P.Blakely.5@nd.edu)> wrote:

            Attached are an updated[ fort.13](https://drive.google.com/file/d/1oTLwS_rGlAI8WaUgVBi_P8VVN29NjQU_/view?usp=drive_web) and[ fort.14](https://drive.google.com/file/d/1gWq6S-8MYo2SRhOawvIlz85WXgFhInHv/view?usp=drive_web) with the advection state nodal attribute added. You will need to use this fort.14 because the nodal numbering is different than the one that you presently have.
             fort.13
             fort.14


            -- 
            -------------------------------------------------------------------------------------------------
            Coleman Blakely
            Ph.D. Student
            Department of Civil and Environmental Engineering and Earth Sciences
            University of Notre Dame
            [cblakely@nd.edu](mailto:cblakely@nd.edu) | 775-848-2587
            -------------------------------------------------------------------------------------------------



    -- 
    -------------------------------------------------------------------------------------------------
    Coleman Blakely
    Ph.D. Student
    Department of Civil and Environmental Engineering and Earth Sciences
    University of Notre Dame
    [cblakely@nd.edu](mailto:cblakely@nd.edu) | 775-848-2587
    -------------------------------------------------------------------------------------------------

**Comment by pvelissariou1** [comment]
Here is a list of the nodes (removed repeated entries) where I get the warning messages (starting at the top, this is the node where the warning first appeared):
4429485
3025366
3043922
1204504
4429486
3043921
1204505
1233355
1218800
1233356
1218799
1190483
4446043
4446044
5175433
5192223
5175430
3941163
3941162
3627599
5192227
730276
730277
3941161
1800560
6006943
1817076
5140186
3504625
5157340
1884504
3504621
1901669
5140513
5157339
3972905
5123281
1800559
5140187
1884503
3203769
3956942
3627871
3645260
3485363
1784282
408320
411716
439764
1768001
1784281
1901670
3194461
3501842
3485362
3956941
3697284
3714205
1867412
1751804
5174276
1768002
4477540
3925397
4477539
4494254
3972906
3128021
5123282
4477538
3128022
4477537
50136
49697
3968224
50588
50132
53311
3108072
1239263
50584
1316602
1028875
450600
5273493
5273492
1254422
1254424
1254428
1269770
1300797
1254432
1269779
1254430
1269781
1254434
1254435
1254433
1239275
5289049
1239273
1239271
1239280
1239272
1224447
1254425
5289047
1300799
1239274
1150107
1150132
1150131
1163184
49261
3697282
1269783
51077
49691
1239283
1285210
1300798
1285219
1285220
1300808
1300809
1316587
1316585
1316586
1239260
1224450
1332462
1224449
1239264
50137
50587
51071
48417
48416
1254423
1239262
1239261
1224446
1285208
1224444
1209976
1209978
1195727
627344
3680077
61320
62263
742932
3988916
461302
749405
63196
62264
62262
3952236
50131
48840
47598
48002
48001
48000
47595
47596
47191
47589
47190
47996
47588
47590
47186
50582
51070
51076
50585
51072
50581
51594
47594
47189
51079
52163
51602
6007056
6007057
6006942
6006826
6006929
6007044
5128916
5076314
5094049
5076315
52675
1300796
1300807
1316578
1316576
1285205
1332454
1300794
1316579
1332456
1300801
1348391
1332455
1348392
108844
1364630
107673
108836
108837
107668
1348393
439765
5928625
432570
53315
432571
436143
464817
61329
436142
53975
1401695
1285209
1224458
1224459
1224456
1224445
1239268
3968189
1285207
62256
1269769
1254429
1239258
1209971
1224442
1168446
1168445
1181881
1168442
1195723
64111
1195726
1129230
1209975
1269775
1224440
1209965
1239256
1239255
1224438
1285203
1285201
1300785
408326
408321
2028590
655777
650260
2010735
1316573
1316574
1300792
1300791
5928036
1074757
63189
2028589
2010736
2046451
3972907
1269778
1269777
1239270
1285204
1224454
5174274
1224441
65066
1224448
1224451
1209972
66032
1224439
66028
51595
1209969
1195719
1195718
1181876
53422
19072
65065
53423
53424
64115
65062
63193
63197
63194
1224443
51596
51598
1300790
1285202
1316572
632600
632601
622195
622198
617134
1209970
1066943
11289
11130
11129
10977
1069480
10976
10833
2117588
627345
617136
622202
769280
667065
655891
650371
672837
672844
672843
678622
678621
2064296
2082077
2171410
798031
2082076
2064297
2171408
2099801
2171409
2153440
2046450
2135537
2117587
2153439
5157337
110010
107675
107677
111241
6007163
5928624
6007165
5928035
6007166
6007164
6007267
6007376
2135538
3925396
6006823
107669
112501
112500
111244
110021
112504
111248
110014
2099802
112499
461303
2189463
5111556
108845
110011
108838
108839
107670
106514
106513
54698
53992
6006941
411718
404948
411719
411722
404942
408319
401552
408327
411714
2207601
2189464
106522
107667
110020
61327
5928033
56207
6006940
6007054
56206
56205
3465665
316572
1057592
1225197
1034492
6007074
1023342
1023338
1057596
6007180
1332794
1057594
411721
1069487
1069489
55432
1069486
54697
1081602
107676
110013
57807
627352
632603
61326
62254
56999
55433
55435
53990
63195
62261

**Comment by pvelissariou1** [comment]
@cblakely97 @jwesterink @GM-Ling 
Here is a list of the nodes (removed repeated entries) where I get the warning messages (starting at the top, this is the node where the warning first appeared):
4429485
3025366
3043922
1204504
4429486
3043921
1204505
1233355
1218800
1233356
1218799
1190483
4446043
4446044
5175433
5192223
5175430
3941163
3941162
3627599
5192227
730276
730277
3941161
1800560
6006943
1817076
5140186
3504625
5157340
1884504
3504621
1901669
5140513
5157339
3972905
5123281
1800559
5140187
1884503
3203769
3956942
3627871
3645260
3485363
1784282
408320
411716
439764
1768001
1784281
1901670
3194461
3501842
3485362
3956941
3697284
3714205
1867412
1751804
5174276
1768002
4477540
3925397
4477539
4494254
3972906
3128021
5123282
4477538
3128022
4477537
50136
49697
3968224
50588
50132
53311
3108072
1239263
50584
1316602
1028875
450600
5273493
5273492
1254422
1254424
1254428
1269770
1300797
1254432
1269779
1254430
1269781
1254434
1254435
1254433
1239275
5289049
1239273
1239271
1239280
1239272
1224447
1254425
5289047
1300799
1239274
1150107
1150132
1150131
1163184
49261
3697282
1269783
51077
49691
1239283
1285210
1300798
1285219
1285220
1300808
1300809
1316587
1316585
1316586
1239260
1224450
1332462
1224449
1239264
50137
50587
51071
48417
48416
1254423
1239262
1239261
1224446
1285208
1224444
1209976
1209978
1195727
627344
3680077
61320
62263
742932
3988916
461302
749405
63196
62264
62262
3952236
50131
48840
47598
48002
48001
48000
47595
47596
47191
47589
47190
47996
47588
47590
47186
50582
51070
51076
50585
51072
50581
51594
47594
47189
51079
52163
51602
6007056
6007057
6006942
6006826
6006929
6007044
5128916
5076314
5094049
5076315
52675
1300796
1300807
1316578
1316576
1285205
1332454
1300794
1316579
1332456
1300801
1348391
1332455
1348392
108844
1364630
107673
108836
108837
107668
1348393
439765
5928625
432570
53315
432571
436143
464817
61329
436142
53975
1401695
1285209
1224458
1224459
1224456
1224445
1239268
3968189
1285207
62256
1269769
1254429
1239258
1209971
1224442
1168446
1168445
1181881
1168442
1195723
64111
1195726
1129230
1209975
1269775
1224440
1209965
1239256
1239255
1224438
1285203
1285201
1300785
408326
408321
2028590
655777
650260
2010735
1316573
1316574
1300792
1300791
5928036
1074757
63189
2028589
2010736
2046451
3972907
1269778
1269777
1239270
1285204
1224454
5174274
1224441
65066
1224448
1224451
1209972
66032
1224439
66028
51595
1209969
1195719
1195718
1181876
53422
19072
65065
53423
53424
64115
65062
63193
63197
63194
1224443
51596
51598
1300790
1285202
1316572
632600
632601
622195
622198
617134
1209970
1066943
11289
11130
11129
10977
1069480
10976
10833
2117588
627345
617136
622202
769280
667065
655891
650371
672837
672844
672843
678622
678621
2064296
2082077
2171410
798031
2082076
2064297
2171408
2099801
2171409
2153440
2046450
2135537
2117587
2153439
5157337
110010
107675
107677
111241
6007163
5928624
6007165
5928035
6007166
6007164
6007267
6007376
2135538
3925396
6006823
107669
112501
112500
111244
110021
112504
111248
110014
2099802
112499
461303
2189463
5111556
108845
110011
108838
108839
107670
106514
106513
54698
53992
6006941
411718
404948
411719
411722
404942
408319
401552
408327
411714
2207601
2189464
106522
107667
110020
61327
5928033
56207
6006940
6007054
56206
56205
3465665
316572
1057592
1225197
1034492
6007074
1023342
1023338
1057596
6007180
1332794
1057594
411721
1069487
1069489
55432
1069486
54697
1081602
107676
110013
57807
627352
632603
61326
62254
56999
55433
55435
53990
63195
62261

**Comment by cblakely97** [comment]
@pvelissariou1 @GM-Ling @jwesterink

Here is a plot of where those nodes are. The green one is the first node to have an issue. I am guessing this is a wetting/drying problem but I do not think Maria has been having any issues. I will ask her.

![image](https://user-images.githubusercontent.com/47362791/175118317-2f5fd2c7-c523-4219-8814-a86c06f030ae.png)

**Comment by cblakely97** [comment]
@pvelissariou1 Can you share your entire spin up fort.15? I want to try and run it on my end.

**Comment by pvelissariou1** [comment]
I will. I'll also share the final list of offending nodes. Hold on

**Comment by pvelissariou1** [comment]
@cblakely97 I will. I'll also share the final list of offending nodes. Hold on

**Comment by pvelissariou1** [comment]
@cblakely97 Coleman below is the list of the offending nodes. If you can plot all of these nodes that will be very helpful.
I'll email you the fort.15.
4429485
3025366
3043922
1204504
4429486
3043921
1204505
1233355
1218800
1233356
1218799
1190483
4446043
4446044
5175433
5192223
5175430
3941163
3941162
3627599
5192227
730276
730277
3941161
1800560
6006943
1817076
5140186
3504625
5157340
1884504
3504621
1901669
5140513
5157339
3972905
5123281
1800559
5140187
1884503
3203769
3956942
3627871
3645260
3485363
1784282
408320
411716
439764
1768001
1784281
1901670
3194461
3501842
3485362
3956941
3697284
3714205
1867412
1751804
5174276
1768002
4477540
3925397
4477539
4494254
3972906
3128021
5123282
4477538
3128022
4477537
50136
49697
3968224
50588
50132
53311
3108072
1239263
50584
1316602
1028875
450600
5273493
5273492
1254422
1254424
1254428
1269770
1300797
1254432
1269779
1254430
1269781
1254434
1254435
1254433
1239275
5289049
1239273
1239271
1239280
1239272
1224447
1254425
5289047
1300799
1239274
1150107
1150132
1150131
1163184
49261
3697282
1269783
51077
49691
1239283
1285210
1300798
1285219
1285220
1300808
1300809
1316587
1316585
1316586
1239260
1224450
1332462
1224449
1239264
50137
50587
51071
48417
48416
1254423
1239262
1239261
1224446
1285208
1224444
1209976
1209978
1195727
627344
3680077
61320
62263
742932
3988916
461302
749405
63196
62264
62262
3952236
50131
48840
47598
48002
48001
48000
47595
47596
47191
47589
47190
47996
47588
47590
47186
50582
51070
51076
50585
51072
50581
51594
47594
47189
51079
52163
51602
6007056
6007057
6006942
6006826
6006929
6007044
5128916
5076314
5094049
5076315
52675
1300796
1300807
1316578
1316576
1285205
1332454
1300794
1316579
1332456
1300801
1348391
1332455
1348392
108844
1364630
107673
108836
108837
107668
1348393
439765
5928625
432570
53315
432571
436143
464817
61329
436142
53975
1401695
1285209
1224458
1224459
1224456
1224445
1239268
3968189
1285207
62256
1269769
1254429
1239258
1209971
1224442
1168446
1168445
1181881
1168442
1195723
64111
1195726
1129230
1209975
1269775
1224440
1209965
1239256
1239255
1224438
1285203
1285201
1300785
408326
408321
2028590
655777
650260
2010735
1316573
1316574
1300792
1300791
5928036
1074757
63189
2028589
2010736
2046451
3972907
1269778
1269777
1239270
1285204
1224454
5174274
1224441
65066
1224448
1224451
1209972
66032
1224439
66028
51595
1209969
1195719
1195718
1181876
53422
19072
65065
53423
53424
64115
65062
63193
63197
63194
1224443
51596
51598
1300790
1285202
1316572
632600
632601
622195
622198
617134
1209970
1066943
11289
11130
11129
10977
1069480
10976
10833
2117588
627345
617136
622202
769280
667065
655891
650371
672837
672844
672843
678622
678621
2064296
2082077
2171410
798031
2082076
2064297
2171408
2099801
2171409
2153440
2046450
2135537
2117587
2153439
5157337
110010
107675
107677
111241
6007163
5928624
6007165
5928035
6007166
6007164
6007267
6007376
2135538
3925396
6006823
107669
112501
112500
111244
110021
112504
111248
110014
2099802
112499
461303
2189463
5111556
108845
110011
108838
108839
107670
106514
106513
54698
53992
6006941
411718
404948
411719
411722
404942
408319
401552
408327
411714
2207601
2189464
106522
107667
110020
61327
5928033
56207
6006940
6007054
56206
56205
3465665
316572
1057592
1225197
1034492
6007074
1023342
1023338
1057596
6007180
1332794
1057594
411721
1069487
1069489
55432
1069486
54697
1081602
107676
110013
57807
627352
632603
61326
62254
56999
55433
55435
53990
63195
62261
1066944
1069481
1069488
106515
1239269
1224453
1168434
1155236
1168427
1195709
1209960
1209958
1057595
1034493
1195710
106512
56994
1254445
1269787
1254441
1239281
1224465
1224464
6007181
6007075
457744
61321
60414
61328
60421
60412
1285218
1300805
1316583
52676
1300810
53313
54688
54684
53980
55430
56993
55431
56204
56998
57811
56997
56209
55436
56208
75386
337895
344756
344757
344763
341308
107666
354993
344755
334468
351599
106519
5927463
806022
344758
106520
6007055
6007269
798027
467642
348219
329778

**Comment by cblakely97** [comment]
@pvelissariou1 Here is the updated plot. Looks like it is just more nodes in the same areas.
![image](https://user-images.githubusercontent.com/47362791/175128870-0bcea92a-3a8a-4838-bcf6-f4d340be7874.png)

**Comment by pvelissariou1** [comment]
Thank you Coleman, it seems that there are close nodes where the warnings
appear.
The data I supplied are after 9 days of spinup.

Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Project Lead - Coastal Coupling
cell: (205) 227-9141
email: ***@***.***

**Comment by saeed-moghimi-noaa** [comment]
@pvelissariou1 @cblakely97 @mtcontre @GM-Ling @jwesterink @ps2epsi

Takis updates:
- The high elevation happens for 120m mesh even for tidal runs. 
- Takis is using https://github.com/adcirc/adcirc/tree/v56-dev
- Takis is using @cblakely97 provided fort15 options and fort13 data

Next steps:
- [ ]  Would be great if @mtcontre tests 120m mesh with this code. 
* A tidal run and 
* Florence best track.
- [ ]  After this step, @cblakely97 to test the same 120m mesh case with Baroclinic effects 
- [ ] @pvelissariou1 will run the same case with BARDDATA cap

**Comment by saeed-moghimi-noaa** [comment]
follow up here: https://github.com/noaa-ocs-modeling/CoastalApp/discussions/151#discussioncomment-4471658
