### ISSUE TITLE
Regression tests on Github actions

### ISSUE THREAD

**Issue by pvelissariou1** [noaa-ocs-modeling/CoastalApp#113]
Option #1: It seems that the most flexible option for CMMB repos is to use "self hosted runners". This option will require the setup/configuration of a physical/virtual Linux machine with the docker software installed. We might need minimum 8 cores and about 64 GB memory.
This option gives us the flexibility to maintain both the runner machine as well as the container.
The current limit of cpus in (free) github actions for Linux/Windows is 2.
NOTE: we can maintain a Linux VM on the cloud (best approach I think).

Option #2: The other option is paid subscription (using codebase) that provides up to 32 cores. Need to upgrade to non-free organization setup for GitHub. Depending on the configuration of the GitHub organization the charges range: $4-$44 per year/per user. The use of resources cpus/memory is about $0.18/hour (Linux/Windows)

**Comment by saeed-moghimi-noaa** [comment]
@SorooshMani-NOAA 

Hi @pvelissariou1   
Did you update the test branch on github? I would like to take a look on before the meeting.
Thanks,
@saeed-moghimi-noaa

**Comment by saeed-moghimi-noaa** [comment]
@pvelissariou1 
Using PW for automated testing

Here is reference to @SorooshMani-NOAA communications:
[CICD-Workflow.pdf](https://github.com/noaa-ocs-modeling/CoastalApp/files/9046762/CICD-Workflow.pdf)

Github repo to llok at:
https://github.com/parallelworks/test-workflow-action

**Comment by saeed-moghimi-noaa** [comment]
Closed.  Github with current limitations is not ready for the task. Will move to:
* CI (light tests; https://github.com/noaa-ocs-modeling/CoastalApp/issues/114) 
* ParallelWorks (larger tests)

**Comment by saeed-moghimi-noaa** [comment]
Hi Takis,

Based on the number of users would you please provide an estimate for the
year. Can we guess how many tests we need to perform and so on?

Thanks,
-Saeed
______________________________________________________
Saeed Moghimi, PhD
*NOS Storm Surge Modeling
<https://nauticalcharts.noaa.gov/learn/storm-surge-modeling.html> Team Lead*
Coastal Marine Modeling Branch, Coast Survey Development Laboratory, Office
of Coast Survey at NOAA National Ocean Service.
Address: 1315 East West Hwy, Room 6607, Silver Spring, Maryland  20910

Phone: ‪(302) 827-3986

The contents of this message are mine personally and do not necessarily
reflect any position of NOAA.
