### ISSUE TITLE
Automated test for running ATMESH + WW3 + (ADCIRC)

### ISSUE THREAD

**Issue by saeed-moghimi-noaa** [noaa-ocs-modeling/CoastalApp#118]

**Comment by saeed-moghimi-noaa** [comment]
Meetings scheduled with Andre

**Comment by pvelissariou1** [comment]
Meetings with Andre:
1) Tuesday: 08/09/2022
    WW3 and workflow configurations on hera (video recording)
2) Wednesday: 08/10/2022
    WW3 config and simulation setup on hera (video recording)
    *Need to talk with Ali on how to run global WW3 and extract BCs*
    for regional WW3 simulations
3) Friday: 08/12/2022 last meeting (will be recorded)
    WW3+PaHM, ADCIRC+WW3+PaHM simulation configs
    Simulation setup/submit jobs on hera using "coastal"

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Project Lead - Coastal Coupling
cell: (205) 227-9141
email: ***@***.***

**Comment by pvelissariou1** [comment]
WW3 tests will be as follows:
1) PaHM + WW3 only
(PaHM/ATMESH + ADCIRC + WW3 requires 5 cores - not available)

**Comment by saeed-moghimi-noaa** [comment]
Next steps:
- [ ] Test submitting 5 MPI threads to 4 cores on your machine
- [ ] ATMESH + WW3 (3 cores)
- [ ] PaHM + WW3 (3 cores)
- [ ] ATMESH + SCHISM (3 cores)

**Comment by pvelissariou1** [comment]
Updated build scripts of CoastalApp to accommodate externally built ParMETIS to be used with WW3 and SCHISM (optional).
Developed cmake files for ParMETIS/SCHISM were pushed to SCHISM repo (pending approval). These modifications solve the ParMETIS issues in CoastalApp (otherwise the application was broken).

**Comment by saeed-moghimi-noaa** [comment]
On **Hera**:
To have these testes to be able to run semi automatically:
Steps:
- Test with Intel (1st priority)
- Test with GNU
------------------------------------------
- [ ] PaHM
- [ ] ATMESH + ADCIRC
- [ ] PahM + ADCIRC
- [ ] ATMESH + WW3 
- [ ] PaHM + WW3 
- [ ] PaHM + WW3  + ADCIRC
- [ ] Semi automated bash + Job submission on Hera

**Comment by saeed-moghimi-noaa** [comment]
@saeed-moghimi-noaa updates:
-  Start working on this item since Sep 15, 2022
- Added a new branch 'feature/ww3-multi-nodes' at https://github.com/noaa-ocs-modeling/CoastalApp-testsuite.git
- Utilized NSEM-workflow to streamline atmesh, ww3 and adcirc testing
- On hera these tests for Shinecock inlet with multi-cores are finalized:

- [ ] Semi automated bash + Job submission on Hera
- [ ] ATMESH + ADCIRC
- [ ] ATMESH + WW3 
- [ ] ATMESH + ADCIRC + WW3

**Comment by saeed-moghimi-noaa** [comment]
@pvelissariou1 

Following our decision today, we want to concentrate on this action items to get:
-Shinnecock and HSOFS test cases running on Hera using NSEM workflow:

Next steps:
- [ ] ATMESH + ADCIRC  
- [ ] PahM 
- [ ] PahM + ADCIRC   

Pending on @aliabdolali hands-on testing:
- [ ]  ATMESH + WW3 
- [ ] PaHM + WW3 


@pvelissariou1 
Please work in this folder  or let me know where you are working on Hera. so we can cross check
/scratch2/COASTAL/coastal/noscrub/shared/

I am working here:
/scratch2/COASTAL/coastal/noscrub/shared/Saeed.Moghimi/coastalapp_test/r

-Saeed

**Comment by saeed-moghimi-noaa** [comment]
Ali provided a test case and communication is happening as a part of:
https://github.com/noaa-ocs-modeling/CoastalApp/issues/134

**Comment by saeed-moghimi-noaa** [comment]
@pvelissariou1 
Takis todo:
- Merge testes
- merge code to dev
- create main

**Comment by pvelissariou1** [comment]
@pvelissariou1 @saeed-moghimi-noaa 
1) shinnecock test cases are now self contained
2) checking/testing now the config files (fort.15, nems. pahm, etc in all test cases
3) working on updating the run scripts

**Comment by pvelissariou1** [comment]
CoastalApp-testsuite has been updated (first iteration). HSOFS test cases will be incorporated on 12/19/2022. Working on automation of tests.

**Comment by saeed-moghimi-noaa** [comment]
Follow up here: https://github.com/noaa-ocs-modeling/CoastalApp/discussions/150
