### ISSUE TITLE
CoastalApp reconstruction/modularization of the build procedure

### ISSUE THREAD

**Issue by pvelissariou1** [noaa-ocs-modeling/CoastalApp#123]
**_This task will always be considered "In Progress" as it will follow the development of the whole CoastalApp application._**

Task list:

- [ ] Modularize the configuration of each model component
- [ ] Modularize the compilation process of each model component
- [ ] ....

**Comment by saeed-moghimi-noaa** [comment]
Please open a discussion for this topic if necessary. @pvelissariou1
