### ISSUE TITLE
WW3 fails to compile on gnu with gcc>9

### ISSUE THREAD

**Issue by platipodium** [noaa-ocs-modeling/CoastalApp#131]
From `gcc10`,  gfortran requires the `-fallow-argument-mismatch` option to compiler MPI programs, as this has not been fixed upstream by MPI implementations.

In line `cmplr.env` line 184, change the general options to

```
optc='-c -J$path_m -p -g -fno-second-underscore -ffree-line-length-none -fconvert=big-endian -fallow-argument-mismatch'
``` 
Conditional upon gcc version > 9 @awest-noaa

**Comment by platipodium** [comment]
Better yet, make use of `ESMF_F90COMPILEOPTS` ...

**Comment by pvelissariou1** [comment]
This has been fixed in the WW3 version included in CoastalApp.
