### ISSUE TITLE
ADCIRC-WW3 not running without nest.grid file

### ISSUE THREAD

**Issue by sarriegi** [noaa-ocs-modeling/CoastalApp#136]
Hello, I am running Hurricane Florence using the HSOFS mesh. The model runs normally when I initially create the nest.grid file. When I try to run the same case without the nest.grid file though, I get the error messages that are shown in the attached picture. Does anyone know how I could fix this?
![Error_no_nestgrid_ADCIRCWW3](https://user-images.githubusercontent.com/77630268/193054597-92dfaa1a-6ba9-4e76-b204-64f18b96b113.png)
:

**Comment by aliabdolali** [comment]
The wave model should run without nest data. I checked Florence on HSOFS and it worked fine without nest data. 
However, if you want to use open boundary conditions, the index of open boundary nodes should be defined in ww3_grid.inp 
and it should be also identified in HSOFS.msh file. 
The spectral resolution in the open boundary conditions should match the setup. 
Once ww3_bounc or ww3_bound is used to generate nest.ww3, then it should be renamed to the name of grid in ww3_multi.inp.

**Comment by sarriegi** [comment]
Thank you Ali, WW3 indeed runs without the nest.grid file. The coupled
ADCIRC/WW3 however for three different storms (Florence, Michael, Sandy)
and for three different grids, in 2 different clusters, was able to run
with the nest.grid file but was not with the same setup but without the
nest.grid file. The netcdf files that the ww3-bounc file must have
frequency equal or higher than the coupling timestep, otherwise I get the
same error. I still haven't found what I should change in my ADCIRC-WW3
setup so that the nest.grid setup is not necessary. Finally, I remember
thar Guoming's run was not able to complete, but when he used the nest.grid
file, it finished successfully. My runs do not even start however without
the nest.grid file.

Angelos

Στις Τετ, 5 Οκτ 2022, 10:34 π.μ. ο χρήστης Ali.Abdolali <
***@***.***> έγραψε:

**Comment by saeed-moghimi-noaa** [comment]
PLEASE follow up here and do not communicate via emails

https://github.com/noaa-ocs-modeling/CoastalApp/discussions/150
