### ISSUE TITLE
Can't run with IM=511112

### ISSUE THREAD

**Issue by sarriegi** [noaa-ocs-modeling/CoastalApp#141]
Hello, when I try to run ADCIRC-WW3 with IM=511112 in the fort.15 file, I receive this error:
![image](https://user-images.githubusercontent.com/77630268/197810095-5a9bedad-aff5-4457-8d0e-2d73d3ab4767.png)
I receive the same error when I try to run the NEMS.x executable in four ways: 
1) ADCIRC passes variables to WW3 and WW3 passes to ADCIRC.
2) ADCIRC passes to WW3 but WW3 does not pass to ADCIRC.
3) ADCIRC does not pass to WW3 but WW3 passes to ADCIRC.
4) ADCIRC and WW3 do not pass variables to each other.
Does anyone know how I could resolve this issue? @saeed-moghimi-noaa @pvelissariou1

**Comment by sarriegi** [comment]
Thank you @saeed-moghimi-noaa , these are the lines in the PET.log files:
![image](https://user-images.githubusercontent.com/77630268/197875673-5d2ee6d6-cf68-4a62-92f3-58c39c822c05.png)

Angelos

**Comment by saeed-moghimi-noaa** [comment]
@sarriegi  Open an issue on adcirc repo if it is not resolved yet.
