### ISSUE TITLE
Radiation stress is not available in ADCIRC-WW3

### ISSUE THREAD

**Issue by sarriegi** [noaa-ocs-modeling/CoastalApp#142]
Hello, It seems like I cannot have radiation stress as output in ADCIRC-WW3. I get this message in the fort.55 file:
*** WAVEWATCH III WARNING  :
     REQUESTED OUTPUT FIELD SXX WAS NOT RECOGNIZED.

does anyone know how to fix this? 

Angelos

**Comment by saeed-moghimi-noaa** [comment]
It seems like a ww3 question perhaps Ali can help or post it to ww3 user forum! @aliabdolali
