### ISSUE TITLE
ADCIRC-WW3 stopping mid-run.

### ISSUE THREAD

**Issue by sarriegi** [noaa-ocs-modeling/CoastalApp#143]
Hello I am running ADCIRC-WW3 but it stops mid-way through the run. The error that I am getting is this:
![image](https://user-images.githubusercontent.com/77630268/198051574-6b797293-9f35-458a-b023-20207bfe6d7a.png)

If I start the run at a different time, the runs is again approximately at the same date. I thought that the water level or the wave height get really high values around that time, but both outputs seem to have reasonable values. Does anybody know how to deal with this?

**Comment by saeed-moghimi-noaa** [comment]
PLEASE follow up here and do not communicate via emails

https://github.com/noaa-ocs-modeling/CoastalApp/discussions/150
