### ISSUE TITLE
WRST flag in switch file

### ISSUE THREAD

**Issue by sarriegi** [noaa-ocs-modeling/CoastalApp#145]
Hello, I wasn't able to find out what does the WRST flag in the switch file do. I haven't seen it in earlier versions of WW3 or in the WW3 manual.

@saeed-moghimi-noaa @pvelissariou1 @aliabdolali

Angelos

**Comment by aliabdolali** [comment]
It is used in operation for wind in restart files. So removing it does not affect your work
