### ISSUE TITLE
Error in latest develop_build ADCIRC-WW3

### ISSUE THREAD

**Issue by sarriegi** [noaa-ocs-modeling/CoastalApp#146]
Hello, while trying to run the latest develop_build version of ADCIRC-WW3, I encountered the following terminating errors in the PET000.ESMF_LogFile.
![image](https://user-images.githubusercontent.com/77630268/201714668-f8b4fabd-9b2d-433d-b5e4-fdcbaa2c5a1e.png)
In previous versions of ADCIRC-WW3 I wasn't getting these errors. Instead, I was getting something like this, but they were not terminating errors:
![image](https://user-images.githubusercontent.com/77630268/201715008-38a25853-f2f8-4859-9e2c-db8c4e82476c.png)
Do you know what the problem might be?
@saeed-moghimi-noaa @pvelissariou1 @aliabdolali

Angelos

**Comment by pvelissariou1** [comment]
Angelos hi,

I don't know where these field names come from.
In CoastalApp none of these fields are defined or used anywhere.
What is the version of ESMF you are using?
Are you sure that you don't have something funny set in your environment?
We have never seen these field names before.
How did you compile CoastalApp?

Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by sarriegi** [comment]
Hello @pvelissariou1 I am using esmf version 8.0.1. Should I use a different version? I compiled CoastalApp with an already pre installed parmetis library, by setting PARMETISHOME and running the command: 
./build.sh --compiler intel --platform hatteras --component "ADCIRC WW3 ATMESH"

Angelos

**Comment by pvelissariou1** [comment]
Hi Angelos,

This is correct. Make sure to do a full cleaning before any compilation,
running:
./build.sh --compiler intel --platform hatteras --component "ADCIRC WW3
ATMESH" --clean 3

Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by pvelissariou1** [comment]
@Saeed Moghimi - NOAA Affiliate ***@***.***> @sarriegi
The ESMF fields you have issues with:
   wind_and_windstress_misalign_angle, wavz0, charnk, misalg
are not defined or used anywhere in CoastalApp or in ESMF.
So it should be some kind of customization from your part I think.

Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by saeed-moghimi-noaa** [comment]
@sarriegi 

I suggest you to continue using the older version of the CoastalApp that works for you.  @pvelissariou1 need to make sure the minimal configuration for WW3+Atmesh is working 1st. When he finished with the test on his side then you may test your cases perhaps with your upgraded Atmesh.

cc @aliabdolali



Best
@saeed-moghimi-noaa

**Comment by sarriegi** [comment]
Thank you @saeed-moghimi-noaa and @pvelissariou1, I realized now that these fields come from an upgrade that Xuanyu Chen had made to the atmesh.F90 and atmesh_mod.F90 files.

Angelos
