### ISSUE TITLE
Running WW3 with sea-state dependent drag coefficient

### ISSUE THREAD

**Issue by sarriegi** [noaa-ocs-modeling/CoastalApp#147]
Hi, What should I do to run the WW3 version in the CoastalApp (standalone) with a sea state dependent drag coefficient, that follows the GFDL distribution? Should I compile the WW3 code with the FLD1 option in the switch file and then add the 2nd line in the following picture to ww3_grid.inp file? Is this enough?
![image](https://user-images.githubusercontent.com/77630268/204714541-cb0dbced-e049-4b41-9af5-6fd7ec4892d3.png)
@aliabdolali 

Angelos

**Comment by saeed-moghimi-noaa** [comment]
@sarriegi Please ask this in a ww3 forum. @aliabdolali what do you suggest!?
