### ISSUE TITLE
Error while running CoastalApp in new cluster

### ISSUE THREAD

**Issue by sarriegi** [noaa-ocs-modeling/CoastalApp#171]
Hello, when I am running CoastalApp in a new computer I get these error messages in one of the PET*.ESMF_Logfiles.
![image](https://user-images.githubusercontent.com/77630268/228609501-46665a33-5ff3-44d5-9434-b6085bac6e11.png)
Do you have any idea what this could mean? Could the reason be that the esmf library was not compiled appropriately in this particular computer? Or something else?

@pvelissariou1 @saeed-moghimi-noaa @aliabdolali

Angelos

**Comment by pvelissariou1** [comment]
What is the esmf version you are using?

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by sarriegi** [comment]
@pvelissariou1 
Hi Takis, I am using version 8.0.1

Angelos

**Comment by pvelissariou1** [comment]
Angelos,

ESMF 8.0.1 is ok for ADCIRC/ATMESH/WW3. SCHISM requires ESMF >= 8.1.1.
I guess you have cloned a recent version of CoastalApp?

Takis


Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by sarriegi** [comment]
@pvelissariou1 Hi Takis, I was wrong, I apologize. I am using version 8.2.0 in the new cluster. I was using version 8.0.1 in the previous clusters where I was running CoastalApp, where the runs were successful.

Angelos

**Comment by pvelissariou1** [comment]
I believe the interface of ESMF has changed slightly from 8.0.*/8.1.* to
8.2.*. This might be the issue.
Can you post the full error log?

Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by sarriegi** [comment]
@pvelissariou1 Yes Takis, here it is.
[PET096.ESMF_LogFile.txt](https://github.com/noaa-ocs-modeling/CoastalApp/files/11103730/PET096.ESMF_LogFile.txt)

Angelos

**Comment by pvelissariou1** [comment]
Angelos,

I have checked CoastalApp with esmf versions from 8.0.1 to
esmf/8_2_0_beta_snapshot_18.1.
It works fine.
Now, I briefly checked esmf/8_2_0_beta_snapshot_18.1 against esmf/8.2.0 and
I found no significant differences.
Could you please check your configuration files NEMS,model, etc to make
sure that everything is ok?

Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by pvelissariou1** [comment]
Angelos,
Open the esmf.mk file to see how esmf was compiled.

On Wednesday, March 29, 2023, sarriegi ***@***.***> wrote:
> @pvelissariou1 Thank you Takis, I am also seeing this error message:
> <
https://ci4.googleusercontent.com/proxy/azzPjM9QTcxrAh4sjj8f1juiEENlPOd0IOfEXgrSj9wlT2fb3qI5lB51f7nrt3oZ6TX2FVHPsqEj92PKwVPEMbXMV_0qlUhY9rlz-_WLnyvpjtEHQk4U4bC-M6nSKmm2AZDYHZ6m8LhavO1eog1NDD97R3iXnmum=s0-d-e1-ft#https://user-images.githubusercontent.com/77630268/228674576-c2a0de0b-e2e8-4a8e-9df9-77568cbecf37.png
>
> Does this say anything to us? Could it mean that the esmf library was not
compiled with the same environment as the CoastalApp? (I haven't compiled
esmf myself in this cluster, I am just using the esmf.mk file that was
created by someone else already).
>
> Angelos
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.<
https://ci4.googleusercontent.com/proxy/H5a20qHN1ycf5PRa-Au7keWcj1ggNsT-rSWXDCmQVdzn6uBXYAdPRnMqVvwIoJl42sa2urUIE8PiCRE2kLWGpduyuPT4obDxubyZhL_W_UdIwdjLCYTZt3aIqrKaZVDC1dPXT2wb0IzzzmjyaruFOD-ITD_82Xj7PntR3qVGJY0W6imUrhe3Ixcsdmn223Zk3BH7Jon5LAAAMthvQ6B0hUEk0WqF1aNgiyOoseW-XqMPajInDQ=s0-d-e1-ft#https://github.com/notifications/beacon/APC7TPZJFKBWXZHIJGTQRB3W6SUR3A5CNFSM6AAAAAAWMER2FGWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTSYYYAMM.gif>Message
ID: ***@***.***>

-- 
Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by pvelissariou1** [comment]
This simply follows the previous error messages. Please make sure that all
libraries that is, NetCDF/HDF5, ESMF are compiled with the same compiler.

Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by pvelissariou1** [comment]
The issue is considered completed, as the issuer did not report any further problems.
