### ISSUE TITLE
Test NEMS workflow with v55 adcirc for PAC mesh for the PAC storms

### ISSUE THREAD

**Issue by saeed-moghimi-noaa** [noaa-ocs-modeling/CoastalApp#40]

**Comment by saeed-moghimi-noaa** [comment]
Assigned to @ps2epsi

**Comment by saeed-moghimi-noaa** [comment]
Followup on the latest mesh from Maria and William. @wpringle @mtcontre .

**Comment by WPringle** [comment]
PAC mesh from before is located in this google drive folder [link](https://drive.google.com/drive/folders/1G0OZyUHzzBuNR_1u3HBp3AbZJPzkzL3z?usp=sharing).

Do you need an updated version of this based on the recent changes to G-ESTOFS? 
Any requests for other changes?

**Comment by saeed-moghimi-noaa** [comment]
Hi @WPringle 

I suggest to do the subset on the latest Gestofs as we removed some issues for the PAC islands. Do you agree?

-Saeed

**Comment by WPringle** [comment]
I can do that. So you are happy with the domain size etc?

**Comment by saeed-moghimi-noaa** [comment]
Yes please. Thanks.

**Comment by saeed-moghimi-noaa** [comment]
OCS need the ATM interpolated on PAC mesh.  @saeed-moghimi-noaa  follow up from Ali and CA team
