### ISSUE TITLE
set up SCHISM build + tests on Orion w/ sample meshes

### ISSUE THREAD

**Issue by ghost** [noaa-ocs-modeling/CoastalApp#46]
build SCHISM with `feature/schism` and test on `/work/noaa/nosofs/share/models/meshes/hsofs/120m/Subsetted_Florence2018_Test`

**Comment by saeed-moghimi-noaa** [comment]
Hi Zach, Please move this and other SCHISM related issues to  COASTAL Act project for now. Thanks. -Saeed

**Comment by pvelissariou1** [comment]
Closing this issue as completed.
