### ISSUE TITLE
izwh10m is missing for ATMESH leads to segmentation fault on femto

### ISSUE THREAD

**Issue by platipodium** [noaa-ocs-modeling/CoastalApp#66]
Running ATMESH standalone or coupled on femto results in segmentation fault. 

@josephzhang @moghimis @zacharyburnettNOAA @pvelissariou1 

```
/sciclone/home20/clemmen/setups/NEMS/RUN01b/NEMS-SCHISM% ./NEMS-atmesh.x
  FILE_NAME  >
 ./wind_atm_fin_ch_time_vec.nc



------>Advancing ATMESH from: 2020  6  1  0  0  0   0
------------------ATMESH-------------> to: 2020  6  1  1  0  0   0
ATMESH refTime=  1982  9 11  0  0  0   0
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
NEMS-atmesh.x      00000000005375BD  for__signal_handl     Unknown  Unknown
libpthread-2.17.s  00002ABB3642D630  Unknown               Unknown  Unknown
NEMS-atmesh.x      00000000005031C5  Unknown               Unknown  Unknown
libesmf.so         00002ABB374D7E09  _ZN5ESMCI13Method     Unknown  Unknown
libesmf.so         00002ABB374D7D2B  _ZN5ESMCI11Method     Unknown  Unknown
libesmf.so         00002ABB374D7212  c_esmc_methodtabl     Unknown  Unknown
libesmf.so         00002ABB3770D966  esmf_attachmethod     Unknown  Unknown
libesmf.so         00002ABB37F327B9  nuopc_modelbase_m     Unknown  Unknown
libesmf.so         00002ABB37160279  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf.so         00002ABB37163E4B  ESMCI_FTableCallE     Unknown  Unknown
libesmf.so         00002ABB37631365  _ZN5ESMCI2VM5ente     Unknown  Unknown
libesmf.so         00002ABB371618DA  c_esmc_ftablecall     Unknown  Unknown
libesmf.so         00002ABB3785DA81  esmf_compmod_mp_e     Unknown  Unknown
libesmf.so         00002ABB37A59EBF  esmf_gridcompmod_     Unknown  Unknown
libesmf.so         00002ABB37EDC85B  nuopc_driver_mp_r     Unknown  Unknown
libesmf.so         00002ABB37160279  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf.so         00002ABB37163E4B  ESMCI_FTableCallE     Unknown  Unknown
libesmf.so         00002ABB37631365  _ZN5ESMCI2VM5ente     Unknown  Unknown
libesmf.so         00002ABB371618DA  c_esmc_ftablecall     Unknown  Unknown
libesmf.so         00002ABB3785DA81  esmf_compmod_mp_e     Unknown  Unknown
libesmf.so         00002ABB37A59EBF  esmf_gridcompmod_     Unknown  Unknown
NEMS-atmesh.x      00000000004F93A5  Unknown               Unknown  Unknown
libesmf.so         00002ABB37160279  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf.so         00002ABB37163E4B  ESMCI_FTableCallE     Unknown  Unknown
libesmf.so         00002ABB37631365  _ZN5ESMCI2VM5ente     Unknown  Unknown
libesmf.so         00002ABB371618DA  c_esmc_ftablecall     Unknown  Unknown
libesmf.so         00002ABB3785DA81  esmf_compmod_mp_e     Unknown  Unknown
libesmf.so         00002ABB37A59EBF  esmf_gridcompmod_     Unknown  Unknown
NEMS-atmesh.x      00000000004149E3  Unknown               Unknown  Unknown
NEMS-atmesh.x      000000000041241E  Unknown               Unknown  Unknown
libc-2.17.so       00002ABB3B0F5555  __libc_start_main     Unknown  Unknown
NEMS-atmesh.x      0000000000412329  Unknown               Unknown  Unknown
```

**Comment by platipodium** [comment]
Identical problem with WW3DATA component.

**Comment by pvelissariou1** [comment]
Carsten, I am currently checking on these.
Do you have a trace log that you can share?

Thank you
Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Project Lead - Coastal Coupling
USM - Stennis Space Center
cell: (205) 227-9141
email: ***@***.***

**Comment by platipodium** [comment]
My bad, it's all in the PET0.log, `izwh10m` is missing...

```
t connected.
20210702 110305.689 INFO             PET0 atmesh.F90:490 (ATMESH:ATMESH_RealizeFields)ATMESH export Field inst_merid_wind_height10m                                        is not connected.
20210702 110305.689 INFO             PET0 atmesh.F90:508  (ATMESH:ATMESH_RealizeFields) --- OUT---
20210702 110305.689 INFO             PET0 atmesh.F90:432  (ATMESH:RealizeFieldsProvidingGrid) --- initialization phase 2 completed ---
20210702 110305.691 INFO             PET0 atmesh.F90:704  ATMESH currTime =         2020 /           6 /           1             0 :           0 :           0
20210702 110305.691 INFO             PET0  (atmesh_mod:read_atmesh_nc)atmesh file it index >          288
20210702 110305.691 INFO             PET0  (atmesh_mod:read_atmesh_nc) --- read ATMesh netcdf file  ---
20210702 110305.691 ERROR            PET0 ESMF_StateAPI.cppF90:3071 ESMF_StateGet Not found  -  no ESMF_Field found named: izwh10m
20210702 110305.691 ERROR            PET0 atmesh.F90:816 Not found  - Passing error in return code
```

**Comment by platipodium** [comment]
... and for WAV it's similar:

```
20210702 110538.052 INFO             PET0 wav.F90:466  (WAV:RealizeFieldsProvidingGrid) --- initialization phase 2 completed ---
20210702 110538.053 INFO             PET0  (wav_mod:read_ww3_nc)WAV file it index >          288
20210702 110538.054 INFO             PET0  (wav_mod:read_ww3_nc) --- read ww3 netcdf file  ---
20210702 110538.054 ERROR            PET0 ESMF_StateAPI.cppF90:3071 ESMF_StateGet Not found  -  no ESMF_Field found named: sxx
20210702 110538.054 ERROR            PET0 wav.F90:885 Not found  - Passing error in return code
```

**Comment by pvelissariou1** [comment]
If you do an ncdump -h on the wave netcdf file do you get the
variables sxx, sxy, etc?
It seems it can not find the sxx variable in your wave netcdf file.

Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Project Lead - Coastal Coupling
USM - Stennis Space Center
cell: (205) 227-9141
email: ***@***.***

**Comment by pvelissariou1** [comment]
Hi Carsten,

Unfortunately the fields uwnd,vwnd,P and sxx,syy,sxy are hardcoded into
ATMESH
and WW3DATA caps respectively.
I am having similar issues with the PaHM fields as well.
ATMESH, WW3DATA should be more general to work with the different models.
No time to fix this now.
You may want to adjust the SCHISM nuopc cap to accommodate these fields
(temporary fix).
Any suggestions?

Thank you
Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Project Lead - Coastal Coupling
USM - Stennis Space Center
cell: (205) 227-9141
email: ***@***.***

**Comment by platipodium** [comment]
I noticed the hardcoded names.  This problem has been addressed in the `netcdf_input_component` in MOSSCO, where the cap's configuration file can contain a table of variable name mappings.  Should be easy to implement in `ATMESH` and `WW3DATA`.  

See documentation at  http://www.mossco.de/doc/md___volumes__kea_devel__m_o_s_s_c_o_code_src_components_netcdf_input_component.html

and file https://sourceforge.net/p/mossco/code/ci/master/tree/src/components/netcdf_input_component.F90 lines 321ff and 680ff.

**Comment by pvelissariou1** [comment]
Thank you Carsten.

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Project Lead - Coastal Coupling
USM - Stennis Space Center
cell: (205) 227-9141
email: ***@***.***

**Comment by platipodium** [comment]
Easier yet, we can add in `ATMESH` and WW3DATA the `NUOPC_FieldDictionaryAdd` with suitable hardcoded (standard) names for the variables read from `netcdf`.  Whereas the flexible solution in MOSSCO is for general input data, this flexibility is not needed here at this moment.

**Comment by platipodium** [comment]
We should separate this issue in two

1.  avoiding the hardcoded names or properly dealing with them
2.  not throwing SEGFAULT but exiting cleanly

**Comment by pvelissariou1** [comment]
Yes I agree. It is on my todo list. I guess this prohibits SCHISM to use
the NUOPC winds via ATMESH (also the rad. stresses via WW3DATA).

Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Project Lead - Coastal Coupling
USM - Stennis Space Center
cell: (205) 227-9141
email: ***@***.***

**Comment by platipodium** [comment]
OK, I've tried to see this through but haven't been able to spot the point of failure.  

- The netcdf files contain the correct hardcoded variables from `atmesh.F90`
- But within ATMESH, we get a failure to look up the field in its own fieldList of its export State.  

This should therefore be a problem internal to ATMESH and not related to coupling...

```
20210702 110305.691 INFO             PET0  (atmesh_mod:read_atmesh_nc) --- read ATMesh netcdf file  ---
20210702 110305.691 ERROR            PET0 ESMF_StateAPI.cppF90:3071 ESMF_StateGet Not found  -  no ESMF_Field found named: izwh10m
20210702 110305.691 ERROR            PET0 atmesh.F90:816 Not found  - Passing error in return code
```

**Comment by pvelissariou1** [comment]
Carsten, hi

Please check your nems.configure. Had the same problem.
See below the lines in red (RunSequence).
Mine looks like:
# EARTH #
EARTH_component_list: ATM OCN
EARTH_attributes::
  Verbosity = max
::

# OCN #
OCN_model:                      adcirc
OCN_petlist_bounds:             0 10
OCN_attributes::
  Verbosity = max
::

# ATM #
ATM_model:                      atmesh
ATM_petlist_bounds:             11 11
ATM_attributes::
  Verbosity = max
::

# Run Sequence #
runSeq::
  @3600
    ATM -> OCN   :remapMethod=redist
    ATM
    OCN
  @
::

Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Project Lead - Coastal Coupling
USM - Stennis Space Center
cell: (205) 227-9141
email: ***@***.***

**Comment by saeed-moghimi-noaa** [comment]
Should be resolved. Please reopen if it is not. @platipodium
