### ISSUE TITLE
NEMS + ATMESH + SCHISM test case

### ISSUE THREAD

**Issue by saeed-moghimi-noaa** [noaa-ocs-modeling/CoastalApp#95]

**Comment by saeed-moghimi-noaa** [comment]
Please update here: @feiye-vims @josephzhang8

**Comment by saeed-moghimi-noaa** [comment]
@josephzhang8 @platipodium @pvelissariou1 

Working to get ATMESH+SCHISM works with multiple cores.

**Comment by platipodium** [comment]
My status on femto and strand is still that it breaks with multiple procs.  Trying to disentangle Takis's cplList issue but having trouble to see where the issue really lies :=(

**Comment by saeed-moghimi-noaa** [comment]
PLEASE follow up here:
https://github.com/noaa-ocs-modeling/CoastalApp/discussions/150
